const productsData = [
    {
        _id:1,
        name:"product 1",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:20,
        price:200,
        sold:5,
    },
    {
        _id:2,
        name:"product 2",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:202,
        price:2002,
        sold:52,
    },
    {
        _id:3,
        name:"product 3",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:203,
        price:2003,
        sold:53,
    },
    {
        _id:4,
        name:"product 4",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:204,
        price:2004,
        sold:54,
    },
    {
        _id:5,
        name:"product 5",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:205,
        price:2005,
        sold:55,
    },
    {
        _id:6,
        name:"product 6",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:206,
        price:2006,
        sold:56,
    },
    {
        _id:7,
        name:"product 7",
        desc:'lreasfd asdfadsf ladfjasd fasdfdsf asfasdf',
        imgUrl:'url',
        supplier_name:'Arfan Khan',
        quantity:207,
        price:2007,
        sold:57,
    },
]

export default productsData;